<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5EVK54D" failures="2" tests="6" name="Test" time="36.21" errors="0" timestamp="2022-12-16T09:55:15 IST">
  <testcase classname="testngdiscussion.ParallelClassExecution2" name="navToUrl" time="14.665"/>
  <testcase classname="testngdiscussion.ParallelClassExecution2" name="enterData" time="4.101"/>
  <testcase classname="testngdiscussion.ParallelClassExecution1" name="navToUrl" time="21.396">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testngdiscussion.ParallelClassExecution1.navToUrl(ParallelClassExecution1.java:28)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- navToUrl -->
  <testcase classname="testngdiscussion.ParallelClassExecution1" name="enterUsername" time="5.602"/>
  <testcase classname="testngdiscussion.ParallelClassExecution1" name="enterPassword" time="1.019"/>
  <testcase classname="testngdiscussion.ParallelClassExecution1" name="getTitleOfpage" time="8.034">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testngdiscussion.ParallelClassExecution1.getTitleOfpage(ParallelClassExecution1.java:78)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- getTitleOfpage -->
</testsuite> <!-- Test -->
